version: '3'
services:
        app:
                image: bydeinon/node-proxy-server:1.0
                env_file:
                        - .env
                ports:
                        - 8080:8080
